inject ttopen.sql right off starting Mysql instance
teamtalk-remix/teamtalk-ng pull request #5
Opened 2019-07-22 03:00 UTC by shiywang

temporary fix #1, you gonna love my brilliant solution @vfreex lol

2019-07-22 09:08 UTC, vfreex requested changes
The random sleep time should be replaced with a more stable waiting mechanism.
Importing the DB schema without checking the existence of tables will drop all data.

2019-07-22 09:11 UTC, vfreex requested changes

2019-07-22 09:11 UTC, vfreex commented on server/deploy/kubernetes/db-mariadb/db-deploy.yaml
> +          name: teamtalk-ng-db-ttopen
Please add a blank line to the end of the file.

2019-07-22 09:11 UTC, vfreex commented on server/deploy/kubernetes/db-mariadb/db-cm-ttopen.yaml
> +  ttopen.sql: "# ************************************************************\n\
Consider using YAML multiline notation to avoid escape symbols.

2019-07-22 09:19 UTC, vfreex requested changes

2019-07-22 09:19 UTC, vfreex commented on server/deploy/kubernetes/db-mariadb/db-deploy.yaml
> +              command: ["/bin/sh", "-c", "sleep 60; scl enable rh-mariadb102 'mysql -u root teamtalk' < /var/lib/mysql/ttopen.sql"]
If the database already has data and the pod recreates, this will delete all data from the database.
60 second sleep seems random to me.

2019-07-22 13:01 UTC, shiywang commented
@vfreex I switched to use upstream mariahdb which has sql dump by default. PTAL

2019-07-23 03:05 UTC, vfreex commented
LGTM

2019-07-23 03:05 UTC, merged